service: bad-decision-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  profile: personal
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: polls/create.create
    events:
      - http:
          path: polls
          method: post
          cors: true

  list:
    handler: polls/list.list
    events:
      - http:
          path: polls
          method: get
          cors: true

  get:
    handler: polls/get.get
    events:
      - http:
          path: polls/{id}
          method: get
          cors: true

  update:
    handler: polls/update.update
    events:
      - http:
          path: polls/{id}
          method: put
          cors: true

  delete:
    handler: polls/delete.delete
    events:
      - http:
          path: polls/{id}
          method: delete
          cors: true

resources:
  Resources:
    PollsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
